[package]
name = "aoc2021"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "day01"
path = "src/day01/main.rs"

[[bin]]
name = "day02"
path = "src/day02/main.rs"

[[bin]]
name = "day03p1"
path = "src/day03p1/main.rs"

[dependencies]
